-- MySQL Script generated by MySQL Workbench
-- 03/25/15 14:01:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema gestion_clases
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestion_clases` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `gestion_clases` ;

-- -----------------------------------------------------
-- Table `gestion_clases`.`acceso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_clases`.`acceso` ;

CREATE TABLE IF NOT EXISTS `gestion_clases`.`acceso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(20) NOT NULL,
  `contrasena` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
;

-- -----------------------------------------------------
-- Table `gestion_clases`.`tipos_clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_clases`.`tipos_clase` ;

CREATE TABLE IF NOT EXISTS `gestion_clases`.`tipos_clase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(20) NOT NULL,
  `precio` DECIMAL(7,2) NOT NULL,
  `particular_sn` INT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `gestion_clases`.`alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_clases`.`alumnos` ;

CREATE TABLE IF NOT EXISTS `gestion_clases`.`alumnos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `correo_electronico` VARCHAR(50) NULL,
  `descripcion` VARCHAR(50),
  `fecha_alta` DATE NOT NULL,
  `activo_sn` INT(1) NULL DEFAULT 1,
  `es_grupo` INT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
;

-- -----------------------------------------------------
-- Table `gestion_clases`.`dias_semana`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_clases`.`dias_semana` ;

CREATE TABLE IF NOT EXISTS `gestion_clases`.`dias_semana` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `gestion_clases`.`horarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_clases`.`horarios` ;

CREATE TABLE IF NOT EXISTS `gestion_clases`.`horarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hora` VARCHAR(45) NOT NULL,
  `dia_semana` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_horarios_dias_semana`
    FOREIGN KEY (`dia_semana`)
    REFERENCES `gestion_clases`.`dias_semana` (`id`))
;


-- -----------------------------------------------------
-- Table `gestion_clases`.`clases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_clases`.`clases` ;

CREATE TABLE IF NOT EXISTS `gestion_clases`.`clases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `activo_sn` INT(1) NULL DEFAULT 1,
  `num_alumnos` INT(2) NULL DEFAULT 0,
  `horario` INT NOT NULL,
  `tipo_clase` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_clases_horarios1`
    FOREIGN KEY (`horario`)
    REFERENCES `gestion_clases`.`horarios` (`id`),
  CONSTRAINT `fk_clases_tipos_clase1`
    FOREIGN KEY (`tipo_clase`)
    REFERENCES `gestion_clases`.`tipos_clase` (`id`))
;


-- -----------------------------------------------------
-- Table `gestion_clases`.`asistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_clases`.`asistencia` ;

CREATE TABLE IF NOT EXISTS `gestion_clases`.`asistencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `alumno` INT NULL,
  `clase` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_asistencia_alumnos1`
    FOREIGN KEY (`alumno`)
    REFERENCES `gestion_clases`.`alumnos` (`id`),
  CONSTRAINT `fk_asistencia_clases1`
    FOREIGN KEY (`clase`)
    REFERENCES `gestion_clases`.`clases` (`id`))
;


-- -----------------------------------------------------
-- Table `gestion_clases`.`pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_clases`.`pagos` ;

CREATE TABLE IF NOT EXISTS `gestion_clases`.`pagos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mensualidad` VARCHAR(50) NOT NULL,
  `cantidad_pagada` DECIMAL(7,2) NOT NULL,
  `pagado_sn` INT(1) NULL DEFAULT 0,
  `por_pagar` DECIMAL(7,2) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `gestion_clases`.`fechas_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_clases`.`fechas_pago` ;

CREATE TABLE IF NOT EXISTS `gestion_clases`.`fechas_pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mes` VARCHAR(10) NOT NULL,
  `anio` INT(2) NOT NULL,
  PRIMARY KEY (`id`))
;


-- -----------------------------------------------------
-- Table `gestion_clases`.`mensualidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_clases`.`mensualidades` ;

CREATE TABLE IF NOT EXISTS `gestion_clases`.`mensualidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mensualidad` VARCHAR(45) NOT NULL,
  `pago` INT NULL,
  `fecha_pago` INT NOT NULL,
  `asistencia` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_mensualidades_pagos1`
    FOREIGN KEY (`pago`)
    REFERENCES `gestion_clases`.`pagos` (`id`),
  CONSTRAINT `fk_mensualidades_fechas_pago1`
    FOREIGN KEY (`fecha_pago`)
    REFERENCES `gestion_clases`.`fechas_pago` (`id`),
  CONSTRAINT `fk_mensualidades_asistencia1`
    FOREIGN KEY (`asistencia`)
    REFERENCES `gestion_clases`.`asistencia` (`id`))
;

-- INSERTS

INSERT INTO `dias_semana` (`id`, `nombre`) VALUES 
(1,'Lunes'),
(2,'Martes'),
(3,'Miercoles'),
(4,'Jueves'),
(5,'Viernes'),
(6,'Sabado'),
(7,'Domingo');

INSERT INTO `tipos_clase` (`id`,`descripcion`, `precio`, `particular_sn`) VALUES 
(1,'Sevillanas',15.0,0),
(2,'Español y flamenco',15.0,0),
(3,'Clase particular',20.0,1);

INSERT INTO `fechas_pago` (`id`, `mes`, `anio`) VALUES 
(1,'Abril',2015),
(2,'Junio',2015),
(3,'Julio',2015),
(4,'Agosto',2015),
(5,'Septiembre',2015),
(6,'Octubre',2015),
(7,'Noviembre',2015);

INSERT INTO `acceso` (`id`, `usuario`, `contrasena`) VALUES 
(1,'a','1');
