PrimeFaces.locales['es'] = {
	    closeText: 'Cerrar',
	    prevText: 'Anterior',
	    nextText: 'Siguiente',
	    monthNames: ['Enero','Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
	    monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun','Jul','Ago','Sep','Oct','Nov','Dic'],
	    dayNames: ['Domingo','Lunes','Martes','Mircoles','Jueves','Viernes','Sbado'],
	    dayNamesShort: ['Dom','Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab'],
	    dayNamesMin: ['D','L','M','X','J','V','S'],
	    weekHeader: 'Semana',
	    firstDay: 1,
	    isRTL: false,
	    showMonthAfterYear: false,
	    yearSuffix: '',
	    timeOnlyTitle: 'Slo hora',
	    timeText: 'Tiempo',
	    hourText: 'Hora',
	    minuteText: 'Minuto',
	    secondText: 'Segundo',
	    currentText: 'Fecha actual',
	    ampm: false,
	    month: 'Mes',
	    week: 'Semana',
	    day: 'Da',
	    allDayText : 'Todo el da'
};