package gestionclases.persistence.entity;
// Generated 25-mar-2015 23:03:28 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Asistencias generated by hbm2java
 */
@Entity
@Table(name="asistencias")
public class Asistencia  implements Serializable {


    private Integer             id;
    private Alumno              alumno;
    private Clase               clase;
    private Set<Mensualidad>    mensualidades = new HashSet<Mensualidad>(0);

    public Asistencia() {
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="alumno")
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="clase", nullable=false)
    public Clase getClase() {
        return this.clase;
    }
    
    public void setClase(Clase clase) {
        this.clase = clase;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="asistencia")
    public Set<Mensualidad> getMensualidades() {
        return this.mensualidades;
    }
    
    public void setMensualidades(Set<Mensualidad> mensualidades) {
        this.mensualidades = mensualidades;
    }

}


