package gestionclases.persistence.entity;
// Generated 25-mar-2015 23:03:28 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clases generated by hbm2java
 */
@Entity
@Table(name="clases")
public class Clase  implements Serializable {


    private Integer             id;
    private Horario             horario;
    private TipoClase           tipoClase;
    private boolean             activoSn;
    private int                 numAlumnos;
    private Set<Asistencia>     asistencias = new HashSet<Asistencia>(0);

    public Clase() {
    }
	
    
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="horario", nullable=false)
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_clase", nullable=false)
    public TipoClase getTipoClase() {
        return this.tipoClase;
    }
    
    public void setTipoClase(TipoClase tipoClase) {
        this.tipoClase = tipoClase;
    }
    
    @Column(name="activo_sn")
    public boolean getActivoSn() {
        return this.activoSn;
    }
    
    public void setActivoSn(boolean activoSn) {
        this.activoSn = activoSn;
    }
    
    @Column(name="num_alumnos")
    public int getNumAlumnos() {
        return this.numAlumnos;
    }
    
    public void setNumAlumnos(int numAlumnos) {
        this.numAlumnos = numAlumnos;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="clase")
    public Set<Asistencia> getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(Set<Asistencia> asistencias) {
        this.asistencias = asistencias;
    }

}


