package gestionclases.persistence.entity;
// Generated 25-mar-2015 23:03:28 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pagos generated by hbm2java
 */
@Entity
@Table(name="pagos")
public class Pago  implements Serializable {


    private Integer             id;
    private String              mensualidad;
    private Float               cantidadPagada;
    private boolean             pagadoSn;
    private Float               porPagar;
    private Set<Mensualidad>    mensualidades = new HashSet<Mensualidad>(0);

    public Pago() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="mensualidad", nullable=false, length=50)
    public String getMensualidad() {
        return this.mensualidad;
    }
    
    public void setMensualidad(String mensualidad) {
        this.mensualidad = mensualidad;
    }
    
    @Column(name="cantidad_pagada", nullable=false, precision=7)
    public Float getCantidadPagada() {
        return this.cantidadPagada;
    }
    
    public void setCantidadPagada(Float cantidadPagada) {
        this.cantidadPagada = cantidadPagada;
    }
    
    @Column(name="pagado_sn")
    public boolean getPagadoSn() {
        return this.pagadoSn;
    }
    
    public void setPagadoSn(boolean pagadoSn) {
        this.pagadoSn = pagadoSn;
    }
    
    @Column(name="por_pagar", precision=7)
    public Float getPorPagar() {
        return this.porPagar;
    }
    
    public void setPorPagar(Float porPagar) {
        this.porPagar = porPagar;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="pago")
    public Set<Mensualidad> getMensualidades() {
        return this.mensualidades;
    }
    
    public void setMensualidades(Set<Mensualidad> mensualidades) {
        this.mensualidades = mensualidades;
    }

}


