package gestionclases.persistence.entity;
// Generated 25-mar-2015 23:03:28 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TiposClase generated by hbm2java
 */
@Entity
@Table(name="tipos_clase")
public class TipoClase  implements Serializable {


    private Integer         id;
    private String          descripcion;
    private Float           precio;
    private boolean         particularSn;


    public TipoClase() {
    }

	
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="descripcion", nullable=false, length=20)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="precio", nullable=false, precision=7)
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    
    @Column(name="particular_sn")
    public boolean getParticularSn() {
        return this.particularSn;
    }
    
    public void setParticularSn(boolean particularSn) {
        this.particularSn = particularSn;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 41 * hash + Objects.hashCode(this.id);
        hash = 41 * hash + Objects.hashCode(this.descripcion);
        hash = 41 * hash + Objects.hashCode(this.precio);
        hash = 41 * hash + (this.particularSn ? 1 : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TipoClase other = (TipoClase) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.descripcion, other.descripcion)) {
            return false;
        }
        if (!Objects.equals(this.precio, other.precio)) {
            return false;
        }
        if (this.particularSn != other.particularSn) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return this.descripcion;
    }

}


