package reservashotel.persistence.entities;
// Generated 28-feb-2015 21:08:17 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EstadoReserva generated by hbm2java
 */
@Entity
@Table(name = "estados_reserva")
public class EstadoReserva implements Serializable {
    
    private Integer     idEstadoReserva;
    private String      nombre;
    private boolean     activoSn;
    
    public EstadoReserva() {
    }
	
    @Id 
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="id_estado_reserva", nullable=false)
    public Integer getIdEstadoReserva() {
        return this.idEstadoReserva;
    }
    
    public void setIdEstadoReserva(Integer idEstadoReserva) {
        this.idEstadoReserva = idEstadoReserva;
    }

    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="activo_sn", nullable=false)
    public boolean getActivoSn() {
        return this.activoSn;
    }
    
    public void setActivoSn(boolean activoSn) {
        this.activoSn = activoSn;
    }
    
    @Override
    public String toString() {
        return this.nombre;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + Objects.hashCode(this.idEstadoReserva);
        hash = 89 * hash + Objects.hashCode(this.nombre);
        hash = 89 * hash + (this.activoSn ? 1 : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final EstadoReserva other = (EstadoReserva) obj;
        if (!Objects.equals(this.idEstadoReserva, other.idEstadoReserva)) {
            return false;
        }
        if (!Objects.equals(this.nombre, other.nombre)) {
            return false;
        }
        if (this.activoSn != other.activoSn) {
            return false;
        }
        return true;
    }
}


