package reservashotel.persistence.entities;
// Generated 28-feb-2015 21:08:17 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Habitacion generated by hbm2java
 */
@Entity
@Table(name = "habitaciones")
public class Habitacion implements Serializable {

    private Integer         idHabitacion;
    private String          codigo;
    private Boolean         fumadorSn;
    private Boolean         exteriorSn;
    private Boolean         movReducidaSn;
    private Boolean         camaSuplSn;
    private TipoHabitacion  tipoHabitacion;
    private String          descripcion;
    private Boolean         activoSn;
    private Timestamp       timestamp;
    
    public Habitacion() {
    }
   
    @Id 
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="id_habitacion", nullable=false)
    public Integer getIdHabitacion() {
        return this.idHabitacion;
    }
    
    public void setIdHabitacion(Integer idHabitacion) {
        this.idHabitacion = idHabitacion;
    }

    @Version
    @Column(name="timestamp", nullable=false)
    public Timestamp getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_tipo_habitacion", nullable=false)
    public TipoHabitacion getTipoHabitacion() {
        return this.tipoHabitacion;
    }
    
    public void setTipoHabitacion(TipoHabitacion tipoHabitacion) {
        this.tipoHabitacion = tipoHabitacion;
    }
    
    @Column(name="codigo", nullable=false)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    
    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="fumador_sn")
    public Boolean getFumadorSn() {
        return this.fumadorSn;
    }
    
    public void setFumadorSn(Boolean fumadorSn) {
        this.fumadorSn = fumadorSn;
    }
    
    @Column(name="exterior_sn")
    public Boolean getExteriorSn() {
        return this.exteriorSn;
    }
    
    public void setExteriorSn(Boolean exteriorSn) {
        this.exteriorSn = exteriorSn;
    }

    @Column(name="mov_reducida_sn")
    public Boolean getMovReducidaSn() {
        return movReducidaSn;
    }

    public void setMovReducidaSn(Boolean movReducidaSn) {
        this.movReducidaSn = movReducidaSn;
    }

    @Column(name="cama_supl_sn", nullable=false)
    public Boolean getCamaSuplSn() {
        return camaSuplSn;
    }

    public void setCamaSuplSn(Boolean camaSuplSn) {
        this.camaSuplSn = camaSuplSn;
    }

    @Column(name="activo_sn", nullable=false)
    public Boolean getActivoSn() {
        return this.activoSn;
    }
    
    public void setActivoSn(Boolean activoSn) {
        this.activoSn = activoSn;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 23 * hash + Objects.hashCode(this.idHabitacion);
        hash = 23 * hash + Objects.hashCode(this.codigo);
        
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Habitacion other = (Habitacion) obj;
        if (!Objects.equals(this.idHabitacion, other.idHabitacion)) {
            return false;
        }
        if (!Objects.equals(this.codigo, other.codigo)) {
            return false;
        }
        
        return true;
    }
    
    

}


