package reservashotel.persistence.entities;
// Generated 28-feb-2015 21:08:17 by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ReservaDet generated by hbm2java
 */
@Entity
@Table(name = "reservas_det")
public class ReservaDet implements Serializable {

    private Integer     idReservaDet;
    private Habitacion  habitacion;
    private ReservaCab  reservaCab;

    public ReservaDet() {
    }
   
    @Id 
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="id_reserva_det", nullable=false)
    public Integer getIdReservaDet() {
        return this.idReservaDet;
    }
    
    public void setIdReservaDet(Integer idReservaDet) {
        this.idReservaDet = idReservaDet;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_habitacion", nullable=false)
    public Habitacion getHabitacion() {
        return this.habitacion;
    }
    
    public void setHabitacion(Habitacion habitacion) {
        this.habitacion = habitacion;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_reserva_cab", nullable=false)
    public ReservaCab getReservaCab() {
        return this.reservaCab;
    }
    
    public void setReservaCab(ReservaCab reservaCab) {
        this.reservaCab = reservaCab;
    }

}


