package reservashotel.persistence.entities;
// Generated 28-feb-2015 21:08:17 by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoHabitacion generated by hbm2java
 */
@Entity
@Table(name = "tipos_habitacion")
public class TipoHabitacion implements Serializable {

    private Integer     idTipoHabitacion;
    private String      nombre;
    private Boolean     activoSn;
    private Float       precio;
    
    public TipoHabitacion() {
    }

    @Id 
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="id_tipo_habitacion", nullable=false)
    public Integer getIdTipoHabitacion() {
        return this.idTipoHabitacion;
    }
    
    public void setIdTipoHabitacion(Integer idTipoHabitacion) {
        this.idTipoHabitacion = idTipoHabitacion;
    }
    
    @Column(name="precio", nullable=false)
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }

    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="activo_sn", nullable=false)
    public Boolean getActivoSn() {
        return this.activoSn;
    }
    
    public void setActivoSn(Boolean activoSn) {
        this.activoSn = activoSn;
    }
    
    @Override
    public String toString() {
        return this.getNombre();
    }

}


