package reservashotel.persistence.entities;
// Generated 28-feb-2015 21:08:17 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuarios")
public class Usuario implements Serializable {

    private Integer     idUsuario;
    private String      nombreUsuario;
    private String      contrasena;
    private Date        fechaAlta;
    private Date        fechaBaja;
    private Boolean     activoSn;
    private Date        timestamp;
    
    public Usuario() {
    }

    @Id 
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="id_usuario", nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    @Version
    @Column(name="timestamp", nullable=false)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    
    @Column(name="nombre_usuario",  unique=true, nullable=false)
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    
    @Column(name="contrasena", unique=true, nullable=false)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_alta", nullable=false)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_baja", length=10)
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }
    
    @Column(name="activo_sn", nullable=false)
    public Boolean getActivoSn() {
        return this.activoSn;
    }
    
    public void setActivoSn(Boolean activoSn) {
        this.activoSn = activoSn;
    }

    @Override
    public String toString() {
        return this.nombreUsuario;
    }

}


